import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Link, Route, Routes, useNavigate} from 'react-router-dom';
import {BookOpen, ChevronRight, Code2, FileUp, FlaskConical, Info, Moon, Play, RotateCcw, Sparkles, Sun, TriangleAlert} from 'lucide-react';
import Plot from 'react-plotly.js';
import {Canvas} from '@react-three/fiber';
import {OrbitControls} from '@react-three/drei';
import * as THREE from 'three';
import './styles.css';
import './learn.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
type Method={slug:string; name:string; category:string; description:string; params:Record<string,any>; example:Record<string,any>};
const methods:Method[]=[
 {slug:'gauss-seidel',name:'Gauss–Seidel',category:'Linear systems',description:'Iteratively solve a square system with live convergence.',params:{A:'[[4,1],[2,3]]',b:'[1,2]',x0:'[0,0]',tolerance:1e-8,max_iterations:30},example:{A:'[[4,1],[2,3]]',b:'[1,2]',x0:'[0,0]',tolerance:1e-8,max_iterations:30}},
 {slug:'gauss-jordan',name:'Gauss–Jordan',category:'Linear systems',description:'Reduce an augmented matrix to row-reduced echelon form.',params:{A:'[[2,1],[1,3]]',b:'[1,2]'},example:{A:'[[2,1],[1,3]]',b:'[1,2]'}},
 {slug:'secant',name:'Secant method',category:'Root finding',description:'Find a root without requiring a derivative.',params:{equation:'x^2 - 2',x0:1,x1:2,tolerance:1e-8,max_iterations:30},example:{equation:'x^2 - 2',x0:1,x1:2,tolerance:1e-8,max_iterations:30}},
 {slug:'lagrange',name:'Lagrange interpolation',category:'Interpolation',description:'Construct the polynomial through arbitrary data points.',params:{points:'[[0,0],[1,1],[2,4]]',x:1.5},example:{points:'[[0,0],[1,1],[2,4]]',x:1.5}},
 {slug:'cubic-spline',name:'Cubic spline',category:'Interpolation',description:'Smooth piecewise cubic interpolation with natural or clamped edges.',params:{points:'[[0,0],[1,1],[2,0]]',x:0.5,boundary:'natural'},example:{points:'[[0,0],[1,1],[2,0]]',x:0.5,boundary:'natural'}},
 {slug:'curve-fitting',name:'Curve fitting',category:'Curve fitting',description:'Fit linear, polynomial, exponential, logarithmic, or power models.',params:{points:'[[0,1],[1,3],[2,5]]',model:'linear',degree:2},example:{points:'[[0,1],[1,3],[2,5]]',model:'linear',degree:2}},
 {slug:'trapezoidal',name:'Trapezoidal rule',category:'Integration',description:'Estimate an integral with one or many trapezoids.',params:{equation:'x^2',a:0,b:1,n:8},example:{equation:'x^2',a:0,b:1,n:8}},
 {slug:'simpson',name:"Simpson's 1/3 rule",category:'Integration',description:'Use parabolic panels for accurate composite integration.',params:{equation:'x^2',a:0,b:1,n:10},example:{equation:'x^2',a:0,b:1,n:10}},
 {slug:'gaussian-quadrature',name:'Gaussian quadrature',category:'Integration',description:'Integrate from weighted Legendre nodes.',params:{equation:'x^2',a:0,b:1,points:3},example:{equation:'x^2',a:0,b:1,points:3}},
 {slug:'euler',name:"Euler's method",category:'ODE',description:'Follow the tangent slope step by step.',params:{equation:'x + y',x0:0,y0:1,h:.1,steps:5},example:{equation:'x + y',x0:0,y0:1,h:.1,steps:5}},
 {slug:'modified-euler',name:'Modified Euler',category:'ODE',description:'Predict then correct each ODE step.',params:{equation:'x + y',x0:0,y0:1,h:.1,steps:5},example:{equation:'x + y',x0:0,y0:1,h:.1,steps:5}},
 {slug:'rk4',name:'Fourth-order Runge–Kutta',category:'ODE',description:'Combine four slopes for high-accuracy ODE integration.',params:{equation:'x + y',x0:0,y0:1,h:.1,steps:5},example:{equation:'x + y',x0:0,y0:1,h:.1,steps:5}},
 {slug:'laplace',name:'Laplace equation',category:'PDE',description:'Relax a 2D grid to a harmonic steady state.',params:{nx:20,ny:20,boundary:'{"top":1,"bottom":0,"left":0,"right":0}',tolerance:1e-5,max_iterations:150},example:{nx:20,ny:20,boundary:'{"top":1,"bottom":0,"left":0,"right":0}',tolerance:1e-5,max_iterations:150}},
 {slug:'poisson',name:'Poisson equation',category:'PDE',description:'Solve a source-driven elliptic PDE with finite differences.',params:{source:'1',nx:20,ny:20,boundary:'{}',tolerance:1e-5,max_iterations:150},example:{source:'1',nx:20,ny:20,boundary:'{}',tolerance:1e-5,max_iterations:150}},
 {slug:'heat-equation',name:'1-D heat equation',category:'PDE',description:'Simulate diffusion while checking the stability ratio.',params:{alpha:1,length:1,initial_condition:'sin(pi*x)',left_boundary:0,right_boundary:0,dx:.1,dt:.002,total_time:.1},example:{alpha:1,length:1,initial_condition:'sin(pi*x)',left_boundary:0,right_boundary:0,dx:.1,dt:.002,total_time:.1}}
];
const bySlug=Object.fromEntries(methods.map(m=>[m.slug,m]));
function parseValue(v:any){if(typeof v!=='string')return v; if((v.startsWith('[')||v.startsWith('{'))){try{return JSON.parse(v)}catch{return v}} const n=Number(v); return Number.isNaN(n)?v:n}
function Field({name,value,onChange}:{name:string;value:any;onChange:(v:any)=>void}){return <label className="field"><span>{name.replaceAll('_',' ')}</span>{typeof value==='string'&&value.length>20?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function App(){return <Routes><Route path="*" element={<Shell/>}/></Routes>}
function Shell(){const [dark,setDark]=useState(false); return <div className={dark?'app dark':'app'}><header><Link to="/" className="brand"><span className="logo">∑</span><span>NUMERICAL<br/><b>VISUALIZER</b></span></Link><nav><Link to="/">Solve</Link><Link to="/methods">Methods</Link></nav><button className="icon-btn" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></header><Routes><Route path="/" element={<Solve/>}/><Route path="/methods" element={<MethodsPage/>}/></Routes></div>}
function MethodsPage(){const nav=useNavigate(); return <main className="container"><div className="eyebrow"><BookOpen size={15}/> METHOD LIBRARY</div><h1>15 methods, one clear<br/><em>learning path.</em></h1><p className="lede">Explore the algorithms behind the visualizer. Each method includes a verified example and a live solver.</p><div className="method-grid">{methods.map(m=><article className="method-card" key={m.slug}><div className="card-top"><span className="tag">{m.category}</span><Code2 size={18}/></div><h3>{m.name}</h3><p>{m.description}</p><button className="text-button" onClick={()=>nav(`/?method=${m.slug}`)}>Try example <ChevronRight size={15}/></button></article>)}</div></main>}
function Solve(){const search=new URLSearchParams(location.search); const [selected,setSelected]=useState(search.get('method')||'rk4'); const method=bySlug[selected]; const [params,setParams]=useState<Record<string,any>>({...method.params}); const [result,setResult]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [problem,setProblem]=useState('dy/dx = x + y, y(0) = 1'); const [recommendation,setRecommendation]=useState<any>(null); const [iteration,setIteration]=useState(0); const [fileMessage,setFileMessage]=useState(''); useEffect(()=>{setParams({...bySlug[selected].params});setResult(null);setError('')},[selected]); const categories=[...new Set(methods.map(m=>m.category))];
 const update=(k:string,v:any)=>setParams(p=>({...p,[k]:v})); const solve=async()=>{setLoading(true);setError('');try{const clean=Object.fromEntries(Object.entries(params).map(([k,v])=>[k,parseValue(v)]));const r=await fetch(`${API}/api/methods/${selected}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({params:clean})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Unable to solve');setResult(data);setIteration(Math.min(1,(data.iterations?.length||1)-1))}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const recommend=async()=>{try{const r=await fetch(`${API}/api/recommend`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({problem,compatible_methods:[]})});setRecommendation(await r.json())}catch{setRecommendation({recommended_method:'Fourth-Order Runge-Kutta',reason:'Backend unavailable; deterministic fallback for a first-order ODE.',alternatives:["Euler's Method",'Modified Euler']})}};
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{if(!e.target.files?.[0])return;const fd=new FormData();fd.append('file',e.target.files[0]);try{const r=await fetch(`${API}/api/upload`,{method:'POST',body:fd});setFileMessage((await r.json()).message)}catch{setFileMessage('Upload received locally. Please paste the problem text below and verify every value.')}};
 const rows=result?.iterations||[]; return <main className="container solve-layout"><section className="hero"><div className="eyebrow"><Sparkles size={15}/> UNDERSTAND → SOLVE → VISUALIZE</div><h1>Numerical methods,<br/><em>made visible.</em></h1><p className="lede">A precise workspace for turning equations into intuition—one iteration at a time.</p><div className="input-strip"><textarea value={problem} onChange={e=>setProblem(e.target.value)} placeholder="Type a problem or equation..."/><button className="primary" onClick={recommend}><Sparkles size={16}/> Recommend</button><label className="upload"><FileUp size={17}/> Upload<input type="file" accept=".png,.jpg,.jpeg,.pdf" onChange={upload}/></label></div>{fileMessage&&<p className="muted small">{fileMessage}</p>}{recommendation&&<div className="recommend"><div className="rec-icon"><Sparkles size={18}/></div><div><span className="tag">AI RECOMMENDATION · FALLBACK SAFE</span><h3>{recommendation.recommended_method}</h3><p>{recommendation.reason}</p><button className="text-button" onClick={()=>{const found=methods.find(m=>m.name.toLowerCase()===recommendation.recommended_method.toLowerCase())||methods.find(m=>recommendation.recommended_method.toLowerCase().includes(m.name.toLowerCase().split(' ')[0]));if(found)setSelected(found.slug)}}>Use recommended <ChevronRight size={15}/></button></div></div>}</section><div className="workspace"><aside className="sidebar"><div className="section-label">SELECT METHOD</div>{categories.map(cat=><div className="method-group" key={cat}><div className="group-title">{cat}</div>{methods.filter(m=>m.category===cat).map(m=><button className={selected===m.slug?'method-choice active':'method-choice'} key={m.slug} onClick={()=>setSelected(m.slug)}><span className="dot"/>{m.name}</button>)}</div>)}</aside><section className="solver"><div className="solver-head"><div><span className="tag">{method.category}</span><h2>{method.name}</h2><p>{method.description}</p></div><button className="ghost" onClick={()=>setParams({...method.example})}><RotateCcw size={15}/> Example</button></div><MethodNotes method={method}/><div className="form-card"><div className="field-grid">{Object.entries(params).map(([k,v])=><Field key={k} name={k} value={v} onChange={nv=>update(k,nv)}/>)}</div><button className="solve-button" onClick={solve} disabled={loading}>{loading?'Computing…':<><Play size={17} fill="currentColor"/> Solve method</>}</button>{error&&<div className="error"><TriangleAlert size={17}/>{error}</div>}</div>{result&&<Result result={result} iteration={iteration} setIteration={setIteration}/>} {!result&&<div className="empty"><FlaskConical size={28}/><h3>Ready when you are</h3><p>Run the verified example or enter your own values to see the calculation unfold.</p></div>}</section></div></main>}

function MethodNotes({method}:{method:Method}){const formula=method.category==='ODE'?'yₙ₊₁ = yₙ + h·f(xₙ, yₙ)':method.category==='Integration'?'Integral ≈ weighted sum of f(xᵢ)·Δx':method.category==='PDE'?'Update each grid point from its neighboring finite differences':'Use the method-specific recurrence shown by the iteration table.';return <details className="learn-panel"><summary><BookOpen size={15}/> Learn the method</summary><div className="learn-grid"><div><b>What is it?</b><p>{method.description}</p></div><div><b>Core formula</b><p className="formula">{formula}</p></div><div><b>What to inspect</b><p>Move the iteration slider to compare each calculated state, error, and convergence trend.</p></div></div></details>}
function Result({result,iteration,setIteration}:{result:any;iteration:number;setIteration:(n:number)=>void}){const rows=result.iterations||[];const visible=rows[Math.min(iteration,rows.length-1)]||{};const graph=useMemo(()=>{if(Array.isArray(result.final_result)&&Array.isArray(result.final_result[0]))return <ThreeDSurface data={result.final_result}/>; const xs=rows.map((r:any)=>r.iteration);const ys=rows.map((r:any)=>r.error??r.next_y??r.residual??0);return <Plot data={[{x:xs,y:ys,type:'scatter',mode:'lines+markers',line:{color:'#e56b4f',width:3},marker:{size:6}}]} layout={{height:280,margin:{l:45,r:20,t:25,b:45},paper_bgcolor:'transparent',plot_bgcolor:'transparent',xaxis:{title:{text:'Iteration'}},yaxis:{title:{text:'Error / value'},type:'log'}}} config={{responsive:true}}/>},[result,rows]); return <div className="result"><div className="result-head"><div><span className="tag success">COMPUTATION COMPLETE</span><h2>Result <span>·</span> {String(result.final_result).slice(0,80)}</h2></div><div className="status-pill">{result.metadata?.converged===false?'Max iterations':'Converged'}</div></div><div className="result-grid"><div className="chart-card"><div className="chart-title"><span>{Array.isArray(result.final_result)&&Array.isArray(result.final_result[0])?'Interactive 3D surface':'Convergence'}</span><strong>Iteration {iteration}</strong></div>{graph}</div><div className="chart-card snapshot"><div className="chart-title"><span>Step inspector</span><Info size={16}/></div><pre>{JSON.stringify(visible,null,2)}</pre></div></div><div className="controls"><button onClick={()=>setIteration(0)}>First</button><button onClick={()=>setIteration(Math.max(0,iteration-1))}>Previous</button><button className="control-play" onClick={()=>setIteration(Math.min(rows.length-1,iteration+1))}><Play size={14} fill="currentColor"/> Next</button><button onClick={()=>setIteration(rows.length-1)}>Last</button></div><input className="slider" type="range" min="0" max={Math.max(0,rows.length-1)} value={iteration} onChange={e=>setIteration(Number(e.target.value))}/><div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]||{}).slice(0,8).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,30).map((r:any,i:number)=><tr className={i===iteration?'selected-row':''} key={i}>{Object.keys(rows[0]||{}).slice(0,8).map(k=><td key={k}>{typeof r[k]==='object'?JSON.stringify(r[k]):typeof r[k]==='number'?r[k].toPrecision(7):String(r[k])}</td>)}</tr>)}</tbody></table></div></div>}

function ThreeDSurface({data}:{data:number[][]}){const nx=data[0]?.length||1,ny=data.length;const ref=React.useRef<THREE.Mesh>(null);useEffect(()=>{const mesh=ref.current;if(!mesh)return;const geometry=mesh.geometry as THREE.PlaneGeometry;const vertices=geometry.attributes.position;for(let i=0;i<vertices.count;i++){const col=i%nx,row=Math.floor(i/nx);vertices.setZ(i,(data[ny-1-row]?.[col]||0)*2)}vertices.needsUpdate=true;geometry.computeVertexNormals()},[data,nx,ny]);return <div className="surface"><Canvas camera={{position:[7,6,8],fov:45}}><ambientLight intensity={1.3}/><directionalLight position={[4,5,4]} intensity={2}/><mesh ref={ref} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[8,6,Math.max(1,nx-1),Math.max(1,ny-1)]}/><meshStandardMaterial color="#2c7873" wireframe={false} side={THREE.DoubleSide}/></mesh><OrbitControls enablePan enableZoom enableRotate/></Canvas></div>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
